[package]
name = "emoticon-convert"
version = "0.1.0"
edition = "2021"

[dependencies]
assets-base = { path = "../../game/assets-base" }
assets-splitting = { path = "../../game/assets-splitting" }

image-utils = { path = "../../lib/image-utils" }

clap = { version = "4.5.47", features = ["derive"] }
