[package]
name = "game-config-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
base-io = { path = "../../lib/base-io" }

game-config = { path = "../game-config" }

anyhow = { version = "1.0.99", features = ["backtrace"] }
