[package]
name = "render-game"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
api = { path = "../../../lib/api" }
config = { path = "../../../lib/config" }

api-render-game = { path = "../../../game/api-render-game" }
client-render-game = { path = "../../../game/client-render-game" }
