[package]
name = "editor_wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
ui-base = { path = "../../../lib/ui-base" }
api = { path = "../../../lib/api" }
api-editor = { path = "../../../game/api-editor" }
editor = { path = "../../../game/editor" }

[lib]
crate-type = ["cdylib"]
