[package]
name = "api-render-game"
version = "0.1.0"
edition = "2024"

[dependencies]
client-render-game = { path = "../client-render-game" }
game-config = { path = "../game-config" }
game-interface = { path = "../game-interface" }
api-wasm-macros = { path = "../../lib/api-wasm-macros" }
api = { path = "../../lib/api" }
graphics-types = { path = "../../lib/graphics-types" }
config = { path = "../../lib/config" }

once_cell = "1.21.3"
