[package]
name = "camera"
version = "0.1.0"
edition = "2024"

[dependencies]
graphics = { path = "../../lib/graphics" }
graphics-types = { path = "../../lib/graphics-types" }
hiarc = { path = "../../lib/hiarc", features = ["derive"] }
math = { path = "../../lib/math" }

map = { path = "../map" }
