name: Graphics related bugs
description: Create a graphics related bug report
labels:
  - B - bug
  - DS - graphics
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Description of the problem you're having
    validations:
      required: true
  - type: textarea
    id: device
    attributes:
      label: Device and operating system version
      description: Which devices and operating systems are you seeing the problem on?
      placeholder: |
        Windows 11, AMD RX 6900 XT (driver version: XXX)
    validations:
      required: true
  - type: textarea
    id: ddnet-version
    attributes:
      label: DDNet version
      description: What version of DDNet are you using?
      placeholder: 15.1.0
    validations:
      required: true
