[package]
name = "map-convert-lib"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }

legacy-map = { path = "../../game/legacy-map" }
map = { path = "../../game/map" }
rayon = "1.11.0"
anyhow = { version = "1.0.99", features = ["backtrace"] }
oxipng = { version = "9.1", features = ["parallel"], default-features = false }
ogg-opus = { git = "https://github.com/Jupeyy/ogg-opus.git", branch = "ddnet-rs" }
vorbis_rs = { version = "0.5.5", default-features = false }

[dev-dependencies]
base-fs = { path = "../../lib/base-fs" }
base-io = { path = "../../lib/base-io" }
difference = "2.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
