[package]
name = "graphics-mod"
version = "0.1.0"
edition = "2024"

[dependencies]
api = { path = "../../../lib/api" }
api-macros = { path = "../../../lib/api-macros" }
base = { path = "../../../lib/base" }
graphics = { path = "../../../lib/graphics" }
graphics-backend-traits = { path = "../../../lib/graphics-backend-traits" }
graphics-base-traits = { path = "../../../lib/graphics-base-traits" }
graphics-types = { path = "../../../lib/graphics-types" }
hiarc = { path = "../../../lib/hiarc", features = ["derive"] }
image-utils = { path = "../../../lib/image-utils" }
math = { path = "../../../lib/math" }
pool = { path = "../../../lib/pool", features = ["enable_hiarc"] }

api-state = { path = "../../../game/api-state" }

anyhow = { version = "1.0.99", features = ["backtrace"] }
arrayvec = "0.7.6"
bitflags = { version = "2.9.4", features = ["serde"] }
num-derive = "0.4.2"
num-traits = "0.2.19"
rayon = "1.11.0"
