[package]
name = "legacy-proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
network = { path = "../../lib/network" }
math = { path = "../../lib/math" }
base = { path = "../../lib/base" }
base-io = { path = "../../lib/base-io" }
base-http = { path = "../../lib/base-http" }
pool = { path = "../../lib/pool" }
bin-patch = { path = "../../lib/bin-patch" }

game-network = { path = "../game-network" }
game-server = { path = "../game-server" }
game-interface = { path = "../game-interface" }
game-base = { path = "../game-base" }
legacy-map = { path = "../legacy-map" }
vanilla = { path = "../vanilla" }
map = { path = "../map" }

libtw2-gamenet-ddnet = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }
libtw2-packer = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }
libtw2-snapshot = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }
libtw2-net = { git = "https://github.com/Jupeyy/libtw2.git", rev = "0e6a9e2f21f12bf34efd2da9f41043e1e3de4c57" }

anyhow = { version = "1.0.99", features = ["backtrace"] }
# stuck for compat with libtw2
arrayvec = "=0.5.2"
hexdump = "0.1.2"
bincode = { version = "2.0.1", features = ["serde"] }
sha2 = "0.10.9"
rand = { version = "0.9.2", features = ["thread_rng"] }

log = "0.4.28"
warn = "0.2.2"
rayon = "1.11.0"
tokio = { version = "1.47.1", features = ["rt-multi-thread", "sync", "fs", "time", "macros"] }
futures = "0.3.31"
hex = "0.4.3"
