name: Check-Format

on:
  push:
    branches-ignore:
      - gh-readonly-queue/**
  pull_request:
  merge_group:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        include:
        - os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: |
        rustup toolchain install stable --profile minimal
        rustup component add rustfmt
        cargo install taplo-cli
        cargo install cargo-machete

    - name: Check format
      run: |
        shopt -s globstar
        rustfmt --edition=2024 --check **/**.rs
        taplo fmt --check **/**.toml

    - name: Check unused deps
      run: |
        shopt -s globstar
        cargo machete
